# -*- coding: utf-8 -*-
"""dog-catclassifer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pW3zP4m0ItO1oIkB8_2okkgCquPEcTwA
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
import matplotlib.pyplot as plt

# Load the model
model = tf.keras.models.load_model('/content/cat_dog_classifier.h5')

# Load the image
img_path = '/content/test_img4.jpg'
img = load_img(img_path, target_size= (64,64))

img_array = img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0
prediction = model.predict(img_array)

plt.imshow(img)
plt.axis('off')

class_label = 'Cat' if prediction[0][0] > 0.5 else 'Dog'
plt.title(f'Predicted: {class_label}')

# Show
plt.show()